### PR TITLE
Use python code instead of dd

### PR DESCRIPTION
**Pull request by HemanthJabalpuri**

### CODE REVIEW

**Comment by cmang** [comment]
Hi Hemanth. is there a reason why you closed this pull request and deleted your fork?

If this code is indeed as fast and reliable as using dd, I would be happy to accept the changes.

Thank you

**Comment by HemanthJabalpuri** [comment]
@cmang I just deleted my fork and this pull automatically closed itself😅

**Comment by HemanthJabalpuri** [comment]
When comparing speed, yeah it is more faster than your dd example, because `bs=1` makes dd slow.
But we can make dd faster by using higher block size like
```
dd if="$s_infile" of="$s_outfile" iflag=skip_bytes,count_bytes status=progress bs=4096 skip=$i_first_byte count=$i_file_size
```

**Comment by cmang** [comment]
Thanks for the contribution, Hemanth!

**Pull request merged**
